### PR TITLE
Feature/n+1 capybara

### PR DESCRIPTION
**Pull request by Armynerh**
n+1

Made sure that the N+1 problem is solved when fetching all posts and their comments for a user.
Did not use the bullet gem in this exercise - instead analysed the logs as showed in this [article](https://dev.to/junko911/rails-n-1-queries-and-eager-loading-10eh)
- app's logs before fix
Screenshot 2023-11-21 at 14 20 51

- after the fix
Screenshot 2023-11-21 at 14 33 31

Used Capybara to write integration tests for each view in the project.
User index page
user show page
User post index page:
Post show page:

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @Armynerh and @ahmidou09,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow proper Gitflow
 Please update your pr to follow proper Gitflow, your default branch should be dev not main 👍🏿  
main


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Armynerh** [comment]
@prolajumokeoni Thank you for your response. However, I believe this was a minor error that you could have notified me on and considering this review was made 3 minutes ago, I had already realised the mistake made and rectified it 13minutes ago (10 minutes before your comment was posted).

**Comment by franclobo** [comment]
Hello, @Armynerh it is important that you check your PR is merging into the development branch from the feature branch to have the correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md). It is mandatory for code reviewers to INVALIDATE if any GENERAL REQUIREMENT is not accomplished.

**Review by franclobo — APPROVED** [review]
Hi @Armynerh and @ahmidou09, 

# STATUS: APPROVED 😃 

git-merge

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- Correct Git flow ✔️ 
- Use gem capybara ✔️ 
- All tests passed ✔️ 

## Optional suggestions

- **[OPTIONAL]** Please add your partner's info in the Authors section on your README file for professional documentation 👇🏽 

image


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
